INSERT INTO STATE_MASTER(STATE_ID,STATE_NAME,AREA_CODE) VALUES(1,'NEW YORK',553);
INSERT INTO STATE_MASTER(STATE_ID,STATE_NAME,AREA_CODE) VALUES(2,'CALIFORNIA',469);
INSERT INTO STATE_MASTER(STATE_ID,STATE_NAME,AREA_CODE) VALUES(3,'TEXAS',526);
